name = "cfw-thenews"
account_id = "1c8bd48a67e737cf8de1c2d03e086cee"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat_v2"]

# R2 Bucket bindings (seguindo padrão do projeto waffle)
[[r2_buckets]]
binding = "FILE_STORAGE"
bucket_name = "waffle-files"
preview_bucket_name = "waffle-files"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "thenews-assets"
preview_bucket_name = "thenews-assets-dev"

# browser = { binding = "BROWSER" }

[observability]
enabled = true

[triggers]
crons = ["0 7 * * *"]

# Variáveis não-sensíveis podem ficar aqui
[vars]
NODE_ENV = "production"
GEMINI_ENDPOINT = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent"
PORTAL_BASE_URL = "https://portal.thenews.com"

# Variáveis sensíveis devem ficar no .dev.vars para desenvolvimento
# e ser configuradas via wrangler secret put para produção